---
title: "A Regression Analysis of the Gender Pay Gap"
author: "Maria-Cristiana Gîrjău"
date: "Revised on 2019-09-20"
output: 
  pdf_document:
    fig_height: 4
    fig_width: 6
    df_print: kable
---

```{r, setup, include=FALSE}
# Loading necessary packages
require(readr)
require(mosaic)
require(dplyr)
require(ggplot2)
require(forcats)
require(stringr)
require(purrr)
require(kableExtra)
require(data.table)

# Setting default chunk and display options
knitr::opts_chunk$set(
  # display code as typed
  tidy = F,
  # slightly smaller font for code
  size = "small",
  # tab plain R output
  comment = "\t",
  # center figures
  fig.align = "center",
  # suppress warnings & messages in knitted doc
  warning = F, message = F)   

# greyscale ggplot theme
theme_set(theme_classic())

# not using scientific notation
options(scipen = 1)
```

<!-- This document should include all the code used to wrangle and analze your data. You should comment your code within each code chunk, and you should document your process as you go. This means describing what each code chunk is doing if it's not immediately obvious (e.g., "After reading in the data, we noticed that this categorical variable was being treated as a numeric variable, so we forced it to be a factor instead."), every decision you made (e.g., "In the code below, we dropped every person over 90 years old and collapsed such-and-such categorical variable down to three categories instead of 10."), and what you are gathering from any output (e.g., "The histogram above shows us that the data are skewed right with one extreme outlier around 300."). Only set `echo=F` for code you do not want to receive feedback on. Use `eval=F` if there is code that is not working and that you want help with! -->

# Data wrangling

<!-- Get the data into the format needed for analysis. Any time in other sections that you realize your data should actually look a different way (e.g, maybe you decide you really want to collapse a categorical variable or something), make sure to come back to this section to implement that change from the beginning. This will be an iterative process! -->

```{r, import}
acs_sample_raw_small <- read_csv("data/acs230_3k.csv")
```

```{r, factors, include=FALSE}
# setting factor levels
sex_levels <- c(M = "1",
                "F" = "2")

citizenship_levels <- c("US born" = "1",
                        "territories born" = "2",
                        "aborad born" = "3",
                        naturalized = "4",
                        "not a citizen" = "5")

race_levels <- c(white = "1",
                  black = "2",
                  native = "3",
                  native = "4",
                  native = "5",
                  asian = "6",
                  native = "7",
                  other = "8",
                  multiple = "9")


military_levels <- c(active = "1",
                     past = "2",
                     training = "3",
                     never = "4")

married_levels <- c(married = "1",
                    widowed = "2",
                    divorced = "3",
                    separated = "4",
                    single = "5")

children_age_levels <- c("under six" = "1",
                         "above six" = "2",
                         both = "3",
                         none = "4")

education_levels <- c(none = "1",
                      preschool = "2",
                      kindergarten = "3",
                      "grade 1" = "4",
                      "grade 2" = "5",
                      "grade 3" = "6",
                      "grade 4" = "7",
                      "grade 5" = "8",
                      "grade 6" = "9",
                      "grade 7" = "10",
                      "grade 8" = "11",
                      "grade 9" = "12",
                      "grade 10" = "13",
                      "grade 11" = "14",
                      "grade 12" = "15",
                      "high school" = "16",
                      GED = "17",
                      "less than one year of college" = "18",
                      "more than one year of college" = "19",
                      associate = "20",
                      bachelor = "21",
                      master = "22",
                      professional = "23",
                      doctoral = "24")

degree_levels <- c()

employment_levels <- c("employed working" = "1",
                       "employed not working" = "2",
                       unemployed = "3",
                       "military working" = "4",
                       "military not working" = "5",
                       "not in labor force" = "6")

worker_class_levels <- c()

region_levels <- c(Northeast = "1",
                   Midwest = "2",
                   South = "3",
                   West = "4",
                   "Puerto Rico" = "9")

state_levels <- c(AL = "1",
                  AK = "2",
                  AZ = "4",
                  AR = "5",
                  CA = "6",
                  CO = "8",
                  CT = "9",
                  DE = "10",
                  DC = "11",
                  FL = "12",
                  GA = "13",
                  HI = "15",
                  ID = "16",
                  IL = "17",
                  IN = "18",
                  IA = "19",
                  KS = "20",
                  KY = "21",
                  LA = "22",
                  ME = "23",
                  MD = "24",
                  MA = "25",
                  MI = "26",
                  MN = "27",
                  MS = "28",
                  MO = "29",
                  MT = "30",
                  NE = "31",
                  NV = "32",
                  NH = "33",
                  NJ = "34",
                  NM = "35",
                  NY = "36",
                  NC = "37",
                  ND = "38",
                  OH = "39",
                  OK = "40",
                  OR = "41",
                  PA = "42",
                  RI = "44",
                  SC = "45",
                  SD = "46",
                  TN = "47",
                  TX = "48",
                  UT = "49",
                  VT = "50",
                  VA = "51",
                  WA = "53",
                  WV = "54",
                  WI = "55",
                  WY = "56",
                  "Puerto Rico" = "72")

# must finish recoding industry codes and degree codes,
# as well as other unfinished factors

# must merge degree variables

# expanding sample (?)

```

```{r, variables}
# Wrangling the data
acs_sample <- acs_sample_raw_small %>%
  
  mutate(ADJINC.x = ADJINC.x / 10^6, # adding decimal point to ADJINC
         WAGP = WAGP * ADJINC.x) %>% # adjusting dollar amounts for inflation
  
  # selecting which variables to keep
  select(SEX, AGEP, CIT, RAC1P, MIL, DIS, # general demographics
         MAR, PAOC, NRC, FER, # family and household
         SCHL, FOD1P, FOD2P, SCIENGP, # educational background
         ESR, COW, WKW, WKHP, NAICSP, # employment
         WAGP, # income
         REGION.x, ST.x) %>% # location
  
  # renaming the variables
  rename(sex = SEX,
         age = AGEP,
         citizenship = CIT,
         race = RAC1P,
         military = MIL,
         disabled = DIS,
         married = MAR,
         children_age = PAOC,
         children_no = NRC,
         gave_birth = FER,
         education = SCHL,
         degree_1 = FOD1P,
         degree_2 = FOD2P,
         stem_degree = SCIENGP,
         employment = ESR,
         worker_class = COW,
         weeks_worked = WKW,
         hours_worked = WKHP,
         industry = NAICSP,
         wage_income = WAGP,
         region = REGION.x,
         state = ST.x) %>%
  
  # converting inputs to an appropriate data type
  mutate(sex = as.factor(sex) %>%
           fct_recode(!!!sex_levels),
         citizenship = as.factor(citizenship) %>%
           fct_recode(!!!citizenship_levels),
         race = as.factor(race) %>%
           fct_recode(!!!race_levels),
         military = as.factor(military) %>%
           fct_recode(!!!military_levels),
         married = as.factor(married) %>%
           fct_recode(!!!married_levels),
         children_age = as.factor(children_age) %>%
           fct_recode(!!!children_age_levels),
         education = as.factor(education) %>%
           fct_recode(!!!education_levels),
         employment = as.factor(employment) %>%
           fct_recode(!!!employment_levels),
         region = as.factor(region) %>%
           fct_recode(!!!region_levels),
         state = as.factor(state) %>%
           fct_recode(!!!state_levels),
         gave_birth = ifelse(gave_birth == 1, TRUE, FALSE),
         stem_degree = ifelse(stem_degree == 1, TRUE, FALSE),
         disabled = ifelse(disabled == 1, TRUE, FALSE)) %>%
  
  # filtering the individuals to keep
  filter(!(is.na(wage_income)) & wage_income > 0, # salary income is positive
         employment %in% c("employed working",
                           "employed not working",
                           "military working")) # employed and/or working
  
# must drop unused levels after filtering
```

```{r, remove, include=FALSE}
# removing unused variables
rm(children_age_levels, citizenship_levels, degree_levels, 
     disabled_levels, education_levels, employment_levels,
     gave_birth_levels, married_levels, military_levels,
     race_levels, region_levels, sex_levels, state_levels,
     stem_degree_levels, worker_class_levels)

rm(acs_sample_raw1, acs_sample_raw2)
```

# Data exploration

<!-- Explore distributions and associations graphically and numerically. -->

```{r, functions}
# some functions for repetitive tasks
render_table <- function(data, title = NULL) {
  data %>%
      kable(booktabs = TRUE, caption = title) %>%
      kable_styling(latex_options = "striped")
}
```

## Univariate data exploration

```{r univariate}
# must make graphics nicer - colors, axis labels, titles, captions

# sex --------------------------------------------------------------------
acs_sample %>%
  group_by(sex) %>%
  tally() %>%
  render_table()

ggplot(acs_sample, aes(x = sex)) + 
  geom_bar()

# race -------------------------------------------------------------------
acs_sample %>%
  group_by(race) %>%
  tally() %>%
  render_table()

ggplot(acs_sample, aes(x = race)) + 
  geom_bar()

# income -----------------------------------------------------------------
acs_sample %>%
  favstats(~wage_income, data = .) %>%
  render_table()

ggplot(acs_sample, aes(x = wage_income, y = ..count..)) + 
  geom_density() +
  scale_x_log10() +
  geom_vline(xintercept = median(acs_sample$wage_income))

# age --------------------------------------------------------------------
acs_sample %>%
  favstats(~age, data = .) %>%
  render_table()

ggplot(acs_sample, aes(x = age, y = ..count..)) + 
  geom_density(fill = "aquamarine3")

# region -----------------------------------------------------------------
acs_sample %>%
  group_by(region) %>%
  tally() %>%
  render_table()

ggplot(acs_sample, aes(x = region)) + 
  geom_bar()
```

```{r include=FALSE}
# code I played around with 

# acs_sample %>%
#   filter(wage_income != 0) %>%
#   ggplot(aes(x = wage_income, fill = sex)) +
#   geom_density(alpha = 0.5) + 
#   scale_x_continuous(trans = "log2") +
#   geom_vline(xintercept = median(acs_sample %>% filter(wage_income!=0, sex == "male") %>% .$wage_income)) +
#   geom_vline(xintercept = median(acs_sample %>% filter(wage_income!=0, sex == "female") %>% .$wage_income))
# 
# # add in filtering on education, stem degrees, etc.
# acs_sample %>%
#   filter(hh_income != 0, wage_income != 0) %>%
#   group_by(sex) %>%
#   summarize(median_hh_income = median(hh_income, na.rm = TRUE),
#             median_wage_income = median(wage_income, na.rm = TRUE)) %>%
#   ggplot() +
#   geom_bar(aes(x = sex, y = median_hh_income), stat = "identity", fill = "blue") +
#   geom_bar(aes(x = sex, y = median_wage_income), stat = "identity", fill = "red")
```

# Data analysis

<!-- Perform analyses. -->

# Assessment


\newpage

# Current questions

<!-- If you are running into issues or have wrangling problems outside of your skillset, let me know here how I can help! You can also ask for pointers on how to implement a method that maybe we haven't covered in course but you would like to include. -->
